/* 195 países soberanos (ONU) + Ciudad del Vaticano. Generado a partir de flag-icons (MIT).
   Criterio de inclusión documentado como política editorial explícita en
   docs/decisiones-producto.md — no ampliar sin que el producto lo pida. */
export const COUNTRIES = [
{"code":"dz","name":"Argelia","capital":"Argel","continent":"África","pattern":"crescent-star","palette":"green-white-red","lat":28.03,"lon":1.66},
{"code":"ao","name":"Angola","capital":"Luanda","continent":"África","pattern":"horizontal-bicolor-emblem","palette":"red-black-yellow","lat":-11.2,"lon":17.87},
{"code":"bj","name":"Benín","capital":"Porto Novo","continent":"África","pattern":"mixed-bicolor","palette":"green-yellow-red","lat":9.31,"lon":2.32},
{"code":"bw","name":"Botsuana","capital":"Gaborone","continent":"África","pattern":"horizontal-multi","palette":"blue-black-white","lat":-22.33,"lon":24.68},
{"code":"bf","name":"Burkina Faso","capital":"Uagadugú","continent":"África","pattern":"horizontal-bicolor-star","palette":"red-green-yellow","lat":12.24,"lon":-1.56},
{"code":"bi","name":"Burundi","capital":"Gitega","continent":"África","pattern":"saltire","palette":"red-white-green","lat":-3.37,"lon":29.92},
{"code":"cv","name":"Cabo Verde","capital":"Praia","continent":"África","pattern":"horizontal-multi-star","palette":"blue-white-red","lat":16,"lon":-24.01},
{"code":"cm","name":"Camerún","capital":"Yaundé","continent":"África","pattern":"vertical-tricolor","palette":"green-red-yellow","lat":7.37,"lon":12.35},
{"code":"cf","name":"República Centroafricana","capital":"Bangui","continent":"África","pattern":"mixed-star","palette":"blue-white-green-yellow-red","lat":6.61,"lon":20.94},
{"code":"td","name":"Chad","capital":"Yamena","continent":"África","pattern":"vertical-tricolor","palette":"blue-yellow-red","lat":15.45,"lon":18.73},
{"code":"km","name":"Comoras","capital":"Moroni","continent":"África","pattern":"triangle-hoist-crescent","palette":"green-white-yellow-red-blue","lat":-11.88,"lon":43.87},
{"code":"cg","name":"República del Congo","capital":"Brazzaville","continent":"África","pattern":"diagonal","palette":"green-yellow-red","lat":-0.23,"lon":15.83},
{"code":"cd","name":"República Democrática del Congo","capital":"Kinshasa","continent":"África","pattern":"diagonal-star","palette":"blue-red-yellow","lat":-4.04,"lon":21.76},
{"code":"ci","name":"Costa de Marfil","capital":"Yamusukro","continent":"África","pattern":"vertical-tricolor","palette":"orange-white-green","lat":7.54,"lon":-5.55},
{"code":"dj","name":"Yibuti","capital":"Yibuti","continent":"África","pattern":"triangle-hoist-star","palette":"blue-green-white-red","lat":11.83,"lon":42.59},
{"code":"eg","name":"Egipto","capital":"El Cairo","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"red-white-black","lat":26.82,"lon":30.8},
{"code":"gq","name":"Guinea Ecuatorial","capital":"Malabo","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"green-white-red-blue","lat":1.65,"lon":10.27},
{"code":"er","name":"Eritrea","capital":"Asmara","continent":"África","pattern":"triangle-hoist-emblem","palette":"red-green-blue-yellow","lat":15.18,"lon":39.78},
{"code":"sz","name":"Esuatini","capital":"Mbabane","continent":"África","pattern":"horizontal-multi-emblem","palette":"blue-yellow-red-black","lat":-26.52,"lon":31.47},
{"code":"et","name":"Etiopía","capital":"Adís Abeba","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"green-yellow-red-blue","lat":9.14,"lon":40.49},
{"code":"ga","name":"Gabón","capital":"Libreville","continent":"África","pattern":"horizontal-tricolor","palette":"green-yellow-blue","lat":-0.8,"lon":11.61},
{"code":"gm","name":"Gambia","capital":"Banjul","continent":"África","pattern":"horizontal-multi","palette":"red-blue-green","lat":13.44,"lon":-15.31},
{"code":"gh","name":"Ghana","capital":"Acra","continent":"África","pattern":"horizontal-tricolor-star","palette":"red-yellow-green-black","lat":7.95,"lon":-1.02},
{"code":"gn","name":"Guinea","capital":"Conakri","continent":"África","pattern":"vertical-tricolor","palette":"red-yellow-green","lat":9.95,"lon":-9.7},
{"code":"gw","name":"Guinea-Bisáu","capital":"Bisáu","continent":"África","pattern":"mixed-star","palette":"red-yellow-green-black","lat":11.8,"lon":-15.18},
{"code":"ke","name":"Kenia","capital":"Nairobi","continent":"África","pattern":"horizontal-multi-emblem","palette":"black-red-green-white","lat":-0.02,"lon":37.91},
{"code":"ls","name":"Lesoto","capital":"Maseru","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"blue-white-green-black","lat":-29.61,"lon":28.23},
{"code":"lr","name":"Liberia","capital":"Monrovia","continent":"África","pattern":"canton-stars","palette":"red-white-blue","lat":6.43,"lon":-9.43},
{"code":"ly","name":"Libia","capital":"Trípoli","continent":"África","pattern":"horizontal-tricolor-crescent","palette":"red-black-green-white","lat":26.34,"lon":17.23},
{"code":"mg","name":"Madagascar","capital":"Antananarivo","continent":"África","pattern":"mixed-bicolor","palette":"white-red-green","lat":-18.77,"lon":46.87},
{"code":"mw","name":"Malaui","capital":"Lilongüe","continent":"África","pattern":"horizontal-multi-sun","palette":"black-red-green-white","lat":-13.25,"lon":34.3},
{"code":"ml","name":"Malí","capital":"Bamako","continent":"África","pattern":"vertical-tricolor","palette":"green-yellow-red","lat":17.57,"lon":-4},
{"code":"mr","name":"Mauritania","capital":"Nuakchot","continent":"África","pattern":"crescent-star","palette":"green-yellow-red","lat":21.01,"lon":-10.94},
{"code":"mu","name":"Mauricio","capital":"Port Louis","continent":"África","pattern":"horizontal-multi","palette":"red-blue-yellow-green","lat":-20.35,"lon":57.55},
{"code":"ma","name":"Marruecos","capital":"Rabat","continent":"África","pattern":"star-outline","palette":"red-green","lat":31.79,"lon":-7.09},
{"code":"mz","name":"Mozambique","capital":"Maputo","continent":"África","pattern":"triangle-hoist-emblem","palette":"green-black-yellow-red-white","lat":-18.67,"lon":35.53},
{"code":"na","name":"Namibia","capital":"Windhoek","continent":"África","pattern":"diagonal-sun","palette":"blue-red-green-yellow-white","lat":-22.96,"lon":18.49},
{"code":"ne","name":"Níger","capital":"Niamey","continent":"África","pattern":"horizontal-tricolor-disc","palette":"orange-white-green","lat":17.61,"lon":8.08},
{"code":"ng","name":"Nigeria","capital":"Abuya","continent":"África","pattern":"vertical-tricolor","palette":"green-white","lat":9.08,"lon":8.68},
{"code":"rw","name":"Ruanda","capital":"Kigali","continent":"África","pattern":"horizontal-multi-sun","palette":"blue-yellow-green","lat":-1.94,"lon":29.87},
{"code":"st","name":"Santo Tomé y Príncipe","capital":"Santo Tomé","continent":"África","pattern":"triangle-hoist-stars","palette":"green-yellow-red-black","lat":0.19,"lon":6.61},
{"code":"sn","name":"Senegal","capital":"Dakar","continent":"África","pattern":"vertical-tricolor-star","palette":"green-yellow-red","lat":14.5,"lon":-14.45},
{"code":"sc","name":"Seychelles","capital":"Victoria","continent":"África","pattern":"diagonal-rays","palette":"blue-yellow-red-white-green","lat":-4.68,"lon":55.49},
{"code":"sl","name":"Sierra Leona","capital":"Freetown","continent":"África","pattern":"horizontal-tricolor","palette":"green-white-blue","lat":8.46,"lon":-11.78},
{"code":"so","name":"Somalia","capital":"Mogadiscio","continent":"África","pattern":"single-star","palette":"blue-white","lat":5.15,"lon":46.2},
{"code":"za","name":"Sudáfrica","capital":"Pretoria","continent":"África","pattern":"diagonal-y","palette":"black-green-yellow-white-red-blue","lat":-30.56,"lon":22.94},
{"code":"ss","name":"Sudán del Sur","capital":"Yuba","continent":"África","pattern":"triangle-hoist-star","palette":"black-red-green-blue-yellow-white","lat":6.88,"lon":31.31},
{"code":"sd","name":"Sudán","capital":"Jartum","continent":"África","pattern":"triangle-hoist","palette":"red-white-black-green","lat":12.86,"lon":30.22},
{"code":"tz","name":"Tanzania","capital":"Dodoma","continent":"África","pattern":"diagonal","palette":"green-black-blue-yellow","lat":-6.37,"lon":34.89},
{"code":"tg","name":"Togo","capital":"Lomé","continent":"África","pattern":"canton-star-stripes","palette":"green-yellow-red-white","lat":8.62,"lon":0.82},
{"code":"tn","name":"Túnez","capital":"Túnez","continent":"África","pattern":"crescent-star-disc","palette":"red-white","lat":33.89,"lon":9.54},
{"code":"ug","name":"Uganda","capital":"Kampala","continent":"África","pattern":"horizontal-multi-emblem","palette":"black-yellow-red-white","lat":1.37,"lon":32.29},
{"code":"zm","name":"Zambia","capital":"Lusaka","continent":"África","pattern":"block-stripes-emblem","palette":"green-red-black-orange","lat":-13.13,"lon":27.85},
{"code":"zw","name":"Zimbabue","capital":"Harare","continent":"África","pattern":"triangle-hoist-emblem","palette":"green-yellow-red-black-white","lat":-19.02,"lon":29.15},

{"code":"af","name":"Afganistán","capital":"Kabul","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"black-red-green-white","lat":33.94,"lon":67.71},
{"code":"am","name":"Armenia","capital":"Ereván","continent":"Asia","pattern":"horizontal-tricolor","palette":"red-blue-orange","lat":40.07,"lon":45.04},
{"code":"az","name":"Azerbaiyán","capital":"Bakú","continent":"Asia","pattern":"horizontal-tricolor-crescent","palette":"blue-red-green-white","lat":40.14,"lon":47.58},
{"code":"bh","name":"Baréin","capital":"Manama","continent":"Asia","pattern":"serrated-bicolor","palette":"white-red","lat":25.93,"lon":50.64},
{"code":"bd","name":"Bangladés","capital":"Daca","continent":"Asia","pattern":"circle-disc","palette":"green-red","lat":23.68,"lon":90.36},
{"code":"bt","name":"Bután","capital":"Timbu","continent":"Asia","pattern":"diagonal-dragon","palette":"yellow-orange-white","lat":27.51,"lon":90.43},
{"code":"bn","name":"Brunéi","capital":"Bandar Seri Begawan","continent":"Asia","pattern":"diagonal-emblem","palette":"yellow-white-black-red","lat":4.54,"lon":114.73},
{"code":"kh","name":"Camboya","capital":"Nom Pen","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"blue-red-white","lat":12.57,"lon":104.99},
{"code":"cn","name":"China","capital":"Pekín","continent":"Asia","pattern":"canton-stars","palette":"red-yellow","lat":35.86,"lon":104.2},
{"code":"ge","name":"Georgia","capital":"Tiflis","continent":"Asia","pattern":"cross-other","palette":"white-red","lat":42.32,"lon":43.36},
{"code":"in","name":"India","capital":"Nueva Delhi","continent":"Asia","pattern":"horizontal-tricolor-wheel","palette":"orange-white-green-blue","lat":20.59,"lon":78.96},
{"code":"id","name":"Indonesia","capital":"Yakarta","continent":"Asia","pattern":"horizontal-bicolor","palette":"red-white","lat":-0.79,"lon":113.92},
{"code":"ir","name":"Irán","capital":"Teherán","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"green-white-red","lat":32.43,"lon":53.69},
{"code":"iq","name":"Irak","capital":"Bagdad","continent":"Asia","pattern":"horizontal-tricolor-text","palette":"red-white-black-green","lat":33.22,"lon":43.68},
{"code":"il","name":"Israel","capital":"Jerusalén","continent":"Asia","pattern":"star-of-david","palette":"blue-white","lat":31.05,"lon":34.85},
{"code":"jp","name":"Japón","capital":"Tokio","continent":"Asia","pattern":"circle-disc","palette":"white-red","lat":36.2,"lon":138.25},
{"code":"jo","name":"Jordania","capital":"Amán","continent":"Asia","pattern":"triangle-hoist-star","palette":"black-white-green-red","lat":30.59,"lon":36.24},
{"code":"kz","name":"Kazajistán","capital":"Astaná","continent":"Asia","pattern":"plain-emblem-center","palette":"blue-yellow","lat":48.02,"lon":66.92},
{"code":"kw","name":"Kuwait","capital":"Kuwait","continent":"Asia","pattern":"horizontal-tricolor-trapezoid","palette":"green-white-red-black","lat":29.31,"lon":47.48},
{"code":"kg","name":"Kirguistán","capital":"Biskek","continent":"Asia","pattern":"sun-rays","palette":"red-yellow","lat":41.2,"lon":74.77},
{"code":"la","name":"Laos","capital":"Vientián","continent":"Asia","pattern":"horizontal-tricolor-disc","palette":"red-blue-white","lat":19.86,"lon":102.5},
{"code":"lb","name":"Líbano","capital":"Beirut","continent":"Asia","pattern":"horizontal-tricolor-tree","palette":"red-white-green","lat":33.85,"lon":35.86},
{"code":"my","name":"Malasia","capital":"Kuala Lumpur","continent":"Asia","pattern":"canton-stars-stripes","palette":"red-white-blue-yellow","lat":4.21,"lon":101.98},
{"code":"mv","name":"Maldivas","capital":"Malé","continent":"Asia","pattern":"rectangle-crescent","palette":"red-green-white","lat":3.2,"lon":73.22},
{"code":"mn","name":"Mongolia","capital":"Ulán Bator","continent":"Asia","pattern":"vertical-tricolor-emblem","palette":"red-blue-yellow","lat":46.86,"lon":103.85},
{"code":"mm","name":"Myanmar","capital":"Naipyidó","continent":"Asia","pattern":"horizontal-tricolor-star","palette":"yellow-green-red-white","lat":21.91,"lon":95.96},
{"code":"np","name":"Nepal","capital":"Katmandú","continent":"Asia","pattern":"double-pennant","palette":"red-blue-white","lat":28.39,"lon":84.12},
{"code":"kp","name":"Corea del Norte","capital":"Pionyang","continent":"Asia","pattern":"horizontal-red-band-star","palette":"blue-red-white","lat":40.34,"lon":127.51},
{"code":"om","name":"Omán","capital":"Mascate","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"white-red-green","lat":21.51,"lon":55.92},
{"code":"pk","name":"Pakistán","capital":"Islamabad","continent":"Asia","pattern":"vertical-bicolor-crescent","palette":"green-white","lat":30.38,"lon":69.35},
{"code":"ps","name":"Palestina","capital":"Ramala","continent":"Asia","pattern":"triangle-hoist","palette":"black-white-green-red","lat":31.95,"lon":35.23},
{"code":"ph","name":"Filipinas","capital":"Manila","continent":"Asia","pattern":"horizontal-bicolor-triangle-sun","palette":"blue-red-white-yellow","lat":12.88,"lon":121.77},
{"code":"qa","name":"Catar","capital":"Doha","continent":"Asia","pattern":"serrated-bicolor","palette":"maroon-white","lat":25.35,"lon":51.18},
{"code":"sa","name":"Arabia Saudita","capital":"Riad","continent":"Asia","pattern":"plain-emblem-text","palette":"green-white","lat":23.89,"lon":45.08},
{"code":"sg","name":"Singapur","capital":"Singapur","continent":"Asia","pattern":"horizontal-bicolor-crescent","palette":"red-white","lat":1.35,"lon":103.82},
{"code":"kr","name":"Corea del Sur","capital":"Seúl","continent":"Asia","pattern":"taegeuk","palette":"white-red-blue-black","lat":35.91,"lon":127.77},
{"code":"lk","name":"Sri Lanka","capital":"Sri Jayawardenapura Kotte","continent":"Asia","pattern":"complex-lion","palette":"yellow-maroon-green-orange","lat":7.87,"lon":80.77},
{"code":"sy","name":"Siria","capital":"Damasco","continent":"Asia","pattern":"horizontal-tricolor-stars","palette":"red-white-black-green","lat":34.8,"lon":39},
{"code":"tj","name":"Tayikistán","capital":"Dusambé","continent":"Asia","pattern":"horizontal-tricolor-crown","palette":"red-white-green-yellow","lat":38.86,"lon":71.28},
{"code":"th","name":"Tailandia","capital":"Bangkok","continent":"Asia","pattern":"horizontal-multi","palette":"red-white-blue","lat":15.87,"lon":100.99},
{"code":"tl","name":"Timor Oriental","capital":"Dili","continent":"Asia","pattern":"triangle-star","palette":"red-black-yellow-white","lat":-8.87,"lon":125.73},
{"code":"tr","name":"Turquía","capital":"Ankara","continent":"Asia","pattern":"crescent-star","palette":"red-white","lat":38.96,"lon":35.24},
{"code":"tm","name":"Turkmenistán","capital":"Asjabad","continent":"Asia","pattern":"vertical-band-carpet","palette":"green-red-white","lat":38.97,"lon":59.56},
{"code":"ae","name":"Emiratos Árabes Unidos","capital":"Abu Dabi","continent":"Asia","pattern":"horizontal-tricolor-band","palette":"green-white-black-red","lat":23.42,"lon":53.85},
{"code":"uz","name":"Uzbekistán","capital":"Taskent","continent":"Asia","pattern":"horizontal-tricolor-crescent","palette":"blue-white-green-red","lat":41.38,"lon":64.59},
{"code":"vn","name":"Vietnam","capital":"Hanói","continent":"Asia","pattern":"single-star","palette":"red-yellow","lat":14.06,"lon":108.28},
{"code":"ye","name":"Yemen","capital":"Saná","continent":"Asia","pattern":"horizontal-tricolor","palette":"red-white-black","lat":15.55,"lon":48.52},

{"code":"al","name":"Albania","capital":"Tirana","continent":"Europa","pattern":"horizontal-eagle","palette":"red-black","lat":41.15,"lon":20.17},
{"code":"ad","name":"Andorra","capital":"Andorra la Vieja","continent":"Europa","pattern":"vertical-tricolor-emblem","palette":"blue-yellow-red","lat":42.55,"lon":1.6},
{"code":"at","name":"Austria","capital":"Viena","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white","lat":47.52,"lon":14.55},
{"code":"by","name":"Bielorrusia","capital":"Minsk","continent":"Europa","pattern":"horizontal-bicolor-pattern","palette":"red-green-white","lat":53.71,"lon":27.95},
{"code":"be","name":"Bélgica","capital":"Bruselas","continent":"Europa","pattern":"vertical-tricolor","palette":"black-yellow-red","lat":50.5,"lon":4.47},
{"code":"ba","name":"Bosnia y Herzegovina","capital":"Sarajevo","continent":"Europa","pattern":"diagonal-stars","palette":"blue-yellow-white","lat":43.92,"lon":17.68},
{"code":"bg","name":"Bulgaria","capital":"Sofía","continent":"Europa","pattern":"horizontal-tricolor","palette":"white-green-red","lat":42.73,"lon":25.49},
{"code":"hr","name":"Croacia","capital":"Zagreb","continent":"Europa","pattern":"horizontal-tricolor-shield","palette":"red-white-blue","lat":45.1,"lon":15.2},
{"code":"cy","name":"Chipre","capital":"Nicosia","continent":"Europa","pattern":"plain-emblem-map","palette":"white-green","lat":35.13,"lon":33.43},
{"code":"cz","name":"Chequia","capital":"Praga","continent":"Europa","pattern":"triangle-hoist","palette":"white-red-blue","lat":49.82,"lon":15.47},
{"code":"dk","name":"Dinamarca","capital":"Copenhague","continent":"Europa","pattern":"cross-nordic","palette":"red-white","lat":56.26,"lon":9.5},
{"code":"ee","name":"Estonia","capital":"Tallin","continent":"Europa","pattern":"horizontal-tricolor","palette":"blue-black-white","lat":58.6,"lon":25.01},
{"code":"fi","name":"Finlandia","capital":"Helsinki","continent":"Europa","pattern":"cross-nordic","palette":"white-blue","lat":61.92,"lon":25.75},
{"code":"fr","name":"Francia","capital":"París","continent":"Europa","pattern":"vertical-tricolor","palette":"blue-white-red","lat":46.23,"lon":2.21},
{"code":"de","name":"Alemania","capital":"Berlín","continent":"Europa","pattern":"horizontal-tricolor","palette":"black-red-gold","lat":51.17,"lon":10.45},
{"code":"gr","name":"Grecia","capital":"Atenas","continent":"Europa","pattern":"stripes-canton-cross","palette":"blue-white","lat":39.07,"lon":21.82},
{"code":"hu","name":"Hungría","capital":"Budapest","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-green","lat":47.16,"lon":19.5},
{"code":"is","name":"Islandia","capital":"Reikiavik","continent":"Europa","pattern":"cross-nordic","palette":"blue-red-white","lat":64.96,"lon":-19.02},
{"code":"ie","name":"Irlanda","capital":"Dublín","continent":"Europa","pattern":"vertical-tricolor","palette":"green-white-orange","lat":53.41,"lon":-8.24},
{"code":"it","name":"Italia","capital":"Roma","continent":"Europa","pattern":"vertical-tricolor","palette":"green-white-red","lat":41.87,"lon":12.57},
{"code":"lv","name":"Letonia","capital":"Riga","continent":"Europa","pattern":"horizontal-tricolor","palette":"maroon-white","lat":56.88,"lon":24.6},
{"code":"li","name":"Liechtenstein","capital":"Vaduz","continent":"Europa","pattern":"horizontal-bicolor-crown","palette":"blue-red-gold","lat":47.17,"lon":9.56},
{"code":"lt","name":"Lituania","capital":"Vilna","continent":"Europa","pattern":"horizontal-tricolor","palette":"yellow-green-red","lat":55.17,"lon":23.88},
{"code":"lu","name":"Luxemburgo","capital":"Luxemburgo","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-blue","lat":49.82,"lon":6.13},
{"code":"mt","name":"Malta","capital":"La Valeta","continent":"Europa","pattern":"vertical-bicolor-cross","palette":"white-red","lat":35.94,"lon":14.38},
{"code":"md","name":"Moldavia","capital":"Chisináu","continent":"Europa","pattern":"vertical-tricolor-emblem","palette":"blue-yellow-red","lat":47.41,"lon":28.37},
{"code":"mc","name":"Mónaco","capital":"Mónaco","continent":"Europa","pattern":"horizontal-bicolor","palette":"red-white","lat":43.75,"lon":7.41},
{"code":"me","name":"Montenegro","capital":"Podgorica","continent":"Europa","pattern":"plain-emblem-border","palette":"red-gold","lat":42.71,"lon":19.37},
{"code":"nl","name":"Países Bajos","capital":"Ámsterdam","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-blue","lat":52.13,"lon":5.29},
{"code":"mk","name":"Macedonia del Norte","capital":"Skopie","continent":"Europa","pattern":"sun-rays","palette":"red-yellow","lat":41.61,"lon":21.75},
{"code":"no","name":"Noruega","capital":"Oslo","continent":"Europa","pattern":"cross-nordic","palette":"red-white-blue","lat":60.47,"lon":8.47},
{"code":"pl","name":"Polonia","capital":"Varsovia","continent":"Europa","pattern":"horizontal-bicolor","palette":"white-red","lat":51.92,"lon":19.15},
{"code":"pt","name":"Portugal","capital":"Lisboa","continent":"Europa","pattern":"vertical-bicolor-emblem","palette":"green-red-yellow","lat":39.4,"lon":-8.22},
{"code":"ro","name":"Rumanía","capital":"Bucarest","continent":"Europa","pattern":"vertical-tricolor","palette":"blue-yellow-red","lat":45.94,"lon":24.97},
{"code":"ru","name":"Rusia","capital":"Moscú","continent":"Europa","pattern":"horizontal-tricolor","palette":"white-blue-red","lat":61.52,"lon":105.32},
{"code":"sm","name":"San Marino","capital":"San Marino","continent":"Europa","pattern":"horizontal-bicolor-emblem","palette":"white-blue","lat":43.94,"lon":12.46},
{"code":"rs","name":"Serbia","capital":"Belgrado","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"red-blue-white","lat":44.02,"lon":21.01},
{"code":"sk","name":"Eslovaquia","capital":"Bratislava","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"white-blue-red","lat":48.67,"lon":19.7},
{"code":"si","name":"Eslovenia","capital":"Liubliana","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"white-blue-red","lat":46.15,"lon":15},
{"code":"es","name":"España","capital":"Madrid","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"red-yellow","lat":40.46,"lon":-3.75},
{"code":"se","name":"Suecia","capital":"Estocolmo","continent":"Europa","pattern":"cross-nordic","palette":"blue-yellow","lat":60.13,"lon":18.64},
{"code":"ch","name":"Suiza","capital":"Berna","continent":"Europa","pattern":"cross-other","palette":"red-white","lat":46.82,"lon":8.23},
{"code":"ua","name":"Ucrania","capital":"Kiev","continent":"Europa","pattern":"horizontal-bicolor","palette":"blue-yellow","lat":48.38,"lon":31.17},
{"code":"gb","name":"Reino Unido","capital":"Londres","continent":"Europa","pattern":"union-jack","palette":"blue-red-white","lat":55.38,"lon":-3.44},
{"code":"va","name":"Vaticano","capital":"Ciudad del Vaticano","continent":"Europa","pattern":"vertical-bicolor-emblem","palette":"yellow-white","lat":41.9,"lon":12.45},

{"code":"ca","name":"Canadá","capital":"Ottawa","continent":"América","pattern":"vertical-bicolor-leaf","palette":"red-white","lat":56.13,"lon":-106.35},
{"code":"us","name":"Estados Unidos","capital":"Washington D. C.","continent":"América","pattern":"canton-stars-stripes","palette":"red-white-blue","lat":37.09,"lon":-95.71},
{"code":"mx","name":"México","capital":"Ciudad de México","continent":"América","pattern":"vertical-tricolor-emblem","palette":"green-white-red","lat":23.63,"lon":-102.55},
{"code":"bz","name":"Belice","capital":"Belmopán","continent":"América","pattern":"plain-emblem-border","palette":"blue-red-white","lat":17.19,"lon":-88.5},
{"code":"cr","name":"Costa Rica","capital":"San José","continent":"América","pattern":"horizontal-multi","palette":"blue-white-red","lat":9.75,"lon":-83.75},
{"code":"sv","name":"El Salvador","capital":"San Salvador","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"blue-white-gold","lat":13.79,"lon":-88.9},
{"code":"gt","name":"Guatemala","capital":"Ciudad de Guatemala","continent":"América","pattern":"vertical-tricolor-emblem","palette":"blue-white-green","lat":15.78,"lon":-90.23},
{"code":"hn","name":"Honduras","capital":"Tegucigalpa","continent":"América","pattern":"horizontal-tricolor-stars","palette":"blue-white","lat":15.2,"lon":-86.24},
{"code":"ni","name":"Nicaragua","capital":"Managua","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"blue-white-yellow","lat":12.87,"lon":-85.21},
{"code":"pa","name":"Panamá","capital":"Ciudad de Panamá","continent":"América","pattern":"quartered-stars","palette":"white-blue-red","lat":8.54,"lon":-80.78},
{"code":"ag","name":"Antigua y Barbuda","capital":"Saint John's","continent":"América","pattern":"sun-rays-triangle","palette":"black-blue-white-red-yellow","lat":17.06,"lon":-61.8},
{"code":"bs","name":"Bahamas","capital":"Nasáu","continent":"América","pattern":"horizontal-tricolor-triangle","palette":"blue-yellow-black","lat":25.03,"lon":-77.4},
{"code":"bb","name":"Barbados","capital":"Bridgetown","continent":"América","pattern":"vertical-tricolor-trident","palette":"blue-yellow-black","lat":13.19,"lon":-59.54},
{"code":"cu","name":"Cuba","capital":"La Habana","continent":"América","pattern":"stripes-triangle-star","palette":"blue-white-red","lat":21.52,"lon":-77.78},
{"code":"dm","name":"Dominica","capital":"Roseau","continent":"América","pattern":"plain-emblem-cross","palette":"green-yellow-black-white-red","lat":15.41,"lon":-61.37},
{"code":"do","name":"República Dominicana","capital":"Santo Domingo","continent":"América","pattern":"cross-quartered","palette":"blue-red-white","lat":18.74,"lon":-70.16},
{"code":"gd","name":"Granada","capital":"Saint George's","continent":"América","pattern":"border-triangle-nutmeg","palette":"yellow-green-red","lat":12.26,"lon":-61.6},
{"code":"ht","name":"Haití","capital":"Puerto Príncipe","continent":"América","pattern":"horizontal-bicolor-emblem","palette":"blue-red","lat":18.97,"lon":-72.29},
{"code":"jm","name":"Jamaica","capital":"Kingston","continent":"América","pattern":"saltire","palette":"black-green-yellow","lat":18.11,"lon":-77.3},
{"code":"kn","name":"San Cristóbal y Nieves","capital":"Basseterre","continent":"América","pattern":"diagonal-stars","palette":"green-black-red-yellow","lat":17.36,"lon":-62.78},
{"code":"lc","name":"Santa Lucía","capital":"Castries","continent":"América","pattern":"triangle-emblem","palette":"blue-black-yellow-white","lat":13.91,"lon":-60.98},
{"code":"vc","name":"San Vicente y las Granadinas","capital":"Kingstown","continent":"América","pattern":"vertical-tricolor-diamonds","palette":"blue-yellow-green","lat":12.98,"lon":-61.29},
{"code":"tt","name":"Trinidad y Tobago","capital":"Puerto España","continent":"América","pattern":"diagonal-bicolor","palette":"red-black-white","lat":10.69,"lon":-61.22},
{"code":"ar","name":"Argentina","capital":"Buenos Aires","continent":"América","pattern":"horizontal-tricolor-sun","palette":"blue-white-yellow","lat":-38.42,"lon":-63.62},
{"code":"bo","name":"Bolivia","capital":"Sucre","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"red-yellow-green","lat":-16.29,"lon":-63.59},
{"code":"br","name":"Brasil","capital":"Brasilia","continent":"América","pattern":"plain-emblem-globe","palette":"green-yellow-blue-white","lat":-14.24,"lon":-51.93},
{"code":"cl","name":"Chile","capital":"Santiago","continent":"América","pattern":"quartered-star","palette":"white-red-blue","lat":-35.68,"lon":-71.54},
{"code":"co","name":"Colombia","capital":"Bogotá","continent":"América","pattern":"horizontal-multi","palette":"yellow-blue-red","lat":4.57,"lon":-74.3},
{"code":"ec","name":"Ecuador","capital":"Quito","continent":"América","pattern":"horizontal-multi-emblem","palette":"yellow-blue-red","lat":-1.83,"lon":-78.18},
{"code":"gy","name":"Guyana","capital":"Georgetown","continent":"América","pattern":"triangle-arrowhead","palette":"green-red-yellow-black-white","lat":4.86,"lon":-58.93},
{"code":"py","name":"Paraguay","capital":"Asunción","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"red-white-blue","lat":-23.44,"lon":-58.44},
{"code":"pe","name":"Perú","capital":"Lima","continent":"América","pattern":"vertical-tricolor","palette":"red-white","lat":-9.19,"lon":-75.02},
{"code":"sr","name":"Surinam","capital":"Paramaribo","continent":"América","pattern":"horizontal-multi-star","palette":"green-white-red-yellow","lat":3.92,"lon":-56.03},
{"code":"uy","name":"Uruguay","capital":"Montevideo","continent":"América","pattern":"stripes-sun","palette":"white-blue-yellow","lat":-32.52,"lon":-55.77},
{"code":"ve","name":"Venezuela","capital":"Caracas","continent":"América","pattern":"horizontal-tricolor-stars","palette":"yellow-blue-red-white","lat":6.42,"lon":-66.59},

{"code":"au","name":"Australia","capital":"Canberra","continent":"Oceanía","pattern":"canton-stars","palette":"blue-white-red","lat":-25.27,"lon":133.78},
{"code":"fj","name":"Fiyi","capital":"Suva","continent":"Oceanía","pattern":"canton-shield","palette":"blue-white-red","lat":-16.58,"lon":179.41},
{"code":"ki","name":"Kiribati","capital":"Tarawa Sur","continent":"Oceanía","pattern":"horizontal-sun-bird","palette":"red-yellow-blue-white","lat":-3.37,"lon":-168.73},
{"code":"mh","name":"Islas Marshall","capital":"Majuro","continent":"Oceanía","pattern":"diagonal-star","palette":"blue-orange-white","lat":7.13,"lon":171.18},
{"code":"fm","name":"Micronesia","capital":"Palikir","continent":"Oceanía","pattern":"plain-stars","palette":"blue-white","lat":7.43,"lon":150.55},
{"code":"nr","name":"Nauru","capital":"Yaren","continent":"Oceanía","pattern":"horizontal-star","palette":"blue-yellow-white","lat":-0.52,"lon":166.93},
{"code":"nz","name":"Nueva Zelanda","capital":"Wellington","continent":"Oceanía","pattern":"canton-stars-southern-cross","palette":"blue-white-red","lat":-40.9,"lon":174.89},
{"code":"pw","name":"Palaos","capital":"Ngerulmud","continent":"Oceanía","pattern":"circle-disc","palette":"blue-yellow","lat":7.51,"lon":134.58},
{"code":"pg","name":"Papúa Nueva Guinea","capital":"Port Moresby","continent":"Oceanía","pattern":"diagonal-bicolor-stars","palette":"red-black-yellow-white","lat":-6.31,"lon":143.96},
{"code":"ws","name":"Samoa","capital":"Apia","continent":"Oceanía","pattern":"canton-stars","palette":"red-blue-white","lat":-13.76,"lon":-172.1},
{"code":"sb","name":"Islas Salomón","capital":"Honiara","continent":"Oceanía","pattern":"diagonal-stripe-stars","palette":"blue-green-yellow-white","lat":-9.65,"lon":160.16},
{"code":"to","name":"Tonga","capital":"Nukualofa","continent":"Oceanía","pattern":"canton-cross","palette":"red-white","lat":-21.18,"lon":-175.2},
{"code":"tv","name":"Tuvalu","capital":"Funafuti","continent":"Oceanía","pattern":"canton-stars-map","palette":"blue-white-yellow","lat":-7.11,"lon":177.65},
{"code":"vu","name":"Vanuatu","capital":"Port Vila","continent":"Oceanía","pattern":"diagonal-emblem","palette":"black-red-green-yellow","lat":-15.38,"lon":166.96}
];
