/* 195 países soberanos (ONU) + Ciudad del Vaticano. Generado a partir de flag-icons (MIT). */
export const COUNTRIES = [
{"code":"dz","name":"Argelia","capital":"Argel","continent":"África","pattern":"crescent-star","palette":"green-white-red"},
{"code":"ao","name":"Angola","capital":"Luanda","continent":"África","pattern":"horizontal-bicolor-emblem","palette":"red-black-yellow"},
{"code":"bj","name":"Benín","capital":"Porto Novo","continent":"África","pattern":"mixed-bicolor","palette":"green-yellow-red"},
{"code":"bw","name":"Botsuana","capital":"Gaborone","continent":"África","pattern":"horizontal-multi","palette":"blue-black-white"},
{"code":"bf","name":"Burkina Faso","capital":"Uagadugú","continent":"África","pattern":"horizontal-bicolor-star","palette":"red-green-yellow"},
{"code":"bi","name":"Burundi","capital":"Gitega","continent":"África","pattern":"saltire","palette":"red-white-green"},
{"code":"cv","name":"Cabo Verde","capital":"Praia","continent":"África","pattern":"horizontal-multi-star","palette":"blue-white-red"},
{"code":"cm","name":"Camerún","capital":"Yaundé","continent":"África","pattern":"vertical-tricolor","palette":"green-red-yellow"},
{"code":"cf","name":"República Centroafricana","capital":"Bangui","continent":"África","pattern":"mixed-star","palette":"blue-white-green-yellow-red"},
{"code":"td","name":"Chad","capital":"Yamena","continent":"África","pattern":"vertical-tricolor","palette":"blue-yellow-red"},
{"code":"km","name":"Comoras","capital":"Moroni","continent":"África","pattern":"triangle-hoist-crescent","palette":"green-white-yellow-red-blue"},
{"code":"cg","name":"República del Congo","capital":"Brazzaville","continent":"África","pattern":"diagonal","palette":"green-yellow-red"},
{"code":"cd","name":"República Democrática del Congo","capital":"Kinshasa","continent":"África","pattern":"diagonal-star","palette":"blue-red-yellow"},
{"code":"ci","name":"Costa de Marfil","capital":"Yamusukro","continent":"África","pattern":"vertical-tricolor","palette":"orange-white-green"},
{"code":"dj","name":"Yibuti","capital":"Yibuti","continent":"África","pattern":"triangle-hoist-star","palette":"blue-green-white-red"},
{"code":"eg","name":"Egipto","capital":"El Cairo","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"red-white-black"},
{"code":"gq","name":"Guinea Ecuatorial","capital":"Malabo","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"green-white-red-blue"},
{"code":"er","name":"Eritrea","capital":"Asmara","continent":"África","pattern":"triangle-hoist-emblem","palette":"red-green-blue-yellow"},
{"code":"sz","name":"Esuatini","capital":"Mbabane","continent":"África","pattern":"horizontal-multi-emblem","palette":"blue-yellow-red-black"},
{"code":"et","name":"Etiopía","capital":"Adís Abeba","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"green-yellow-red-blue"},
{"code":"ga","name":"Gabón","capital":"Libreville","continent":"África","pattern":"horizontal-tricolor","palette":"green-yellow-blue"},
{"code":"gm","name":"Gambia","capital":"Banjul","continent":"África","pattern":"horizontal-multi","palette":"red-blue-green"},
{"code":"gh","name":"Ghana","capital":"Acra","continent":"África","pattern":"horizontal-tricolor-star","palette":"red-yellow-green-black"},
{"code":"gn","name":"Guinea","capital":"Conakri","continent":"África","pattern":"vertical-tricolor","palette":"red-yellow-green"},
{"code":"gw","name":"Guinea-Bisáu","capital":"Bisáu","continent":"África","pattern":"mixed-star","palette":"red-yellow-green-black"},
{"code":"ke","name":"Kenia","capital":"Nairobi","continent":"África","pattern":"horizontal-multi-emblem","palette":"black-red-green-white"},
{"code":"ls","name":"Lesoto","capital":"Maseru","continent":"África","pattern":"horizontal-tricolor-emblem","palette":"blue-white-green-black"},
{"code":"lr","name":"Liberia","capital":"Monrovia","continent":"África","pattern":"canton-stars","palette":"red-white-blue"},
{"code":"ly","name":"Libia","capital":"Trípoli","continent":"África","pattern":"horizontal-tricolor-crescent","palette":"red-black-green-white"},
{"code":"mg","name":"Madagascar","capital":"Antananarivo","continent":"África","pattern":"mixed-bicolor","palette":"white-red-green"},
{"code":"mw","name":"Malaui","capital":"Lilongüe","continent":"África","pattern":"horizontal-multi-sun","palette":"black-red-green-white"},
{"code":"ml","name":"Malí","capital":"Bamako","continent":"África","pattern":"vertical-tricolor","palette":"green-yellow-red"},
{"code":"mr","name":"Mauritania","capital":"Nuakchot","continent":"África","pattern":"crescent-star","palette":"green-yellow-red"},
{"code":"mu","name":"Mauricio","capital":"Port Louis","continent":"África","pattern":"horizontal-multi","palette":"red-blue-yellow-green"},
{"code":"ma","name":"Marruecos","capital":"Rabat","continent":"África","pattern":"star-outline","palette":"red-green"},
{"code":"mz","name":"Mozambique","capital":"Maputo","continent":"África","pattern":"triangle-hoist-emblem","palette":"green-black-yellow-red-white"},
{"code":"na","name":"Namibia","capital":"Windhoek","continent":"África","pattern":"diagonal-sun","palette":"blue-red-green-yellow-white"},
{"code":"ne","name":"Níger","capital":"Niamey","continent":"África","pattern":"horizontal-tricolor-disc","palette":"orange-white-green"},
{"code":"ng","name":"Nigeria","capital":"Abuya","continent":"África","pattern":"vertical-tricolor","palette":"green-white"},
{"code":"rw","name":"Ruanda","capital":"Kigali","continent":"África","pattern":"horizontal-multi-sun","palette":"blue-yellow-green"},
{"code":"st","name":"Santo Tomé y Príncipe","capital":"Santo Tomé","continent":"África","pattern":"triangle-hoist-stars","palette":"green-yellow-red-black"},
{"code":"sn","name":"Senegal","capital":"Dakar","continent":"África","pattern":"vertical-tricolor-star","palette":"green-yellow-red"},
{"code":"sc","name":"Seychelles","capital":"Victoria","continent":"África","pattern":"diagonal-rays","palette":"blue-yellow-red-white-green"},
{"code":"sl","name":"Sierra Leona","capital":"Freetown","continent":"África","pattern":"horizontal-tricolor","palette":"green-white-blue"},
{"code":"so","name":"Somalia","capital":"Mogadiscio","continent":"África","pattern":"single-star","palette":"blue-white"},
{"code":"za","name":"Sudáfrica","capital":"Pretoria","continent":"África","pattern":"diagonal-y","palette":"black-green-yellow-white-red-blue"},
{"code":"ss","name":"Sudán del Sur","capital":"Yuba","continent":"África","pattern":"triangle-hoist-star","palette":"black-red-green-blue-yellow-white"},
{"code":"sd","name":"Sudán","capital":"Jartum","continent":"África","pattern":"triangle-hoist","palette":"red-white-black-green"},
{"code":"tz","name":"Tanzania","capital":"Dodoma","continent":"África","pattern":"diagonal","palette":"green-black-blue-yellow"},
{"code":"tg","name":"Togo","capital":"Lomé","continent":"África","pattern":"canton-star-stripes","palette":"green-yellow-red-white"},
{"code":"tn","name":"Túnez","capital":"Túnez","continent":"África","pattern":"crescent-star-disc","palette":"red-white"},
{"code":"ug","name":"Uganda","capital":"Kampala","continent":"África","pattern":"horizontal-multi-emblem","palette":"black-yellow-red-white"},
{"code":"zm","name":"Zambia","capital":"Lusaka","continent":"África","pattern":"block-stripes-emblem","palette":"green-red-black-orange"},
{"code":"zw","name":"Zimbabue","capital":"Harare","continent":"África","pattern":"triangle-hoist-emblem","palette":"green-yellow-red-black-white"},

{"code":"af","name":"Afganistán","capital":"Kabul","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"black-red-green-white"},
{"code":"am","name":"Armenia","capital":"Ereván","continent":"Asia","pattern":"horizontal-tricolor","palette":"red-blue-orange"},
{"code":"az","name":"Azerbaiyán","capital":"Bakú","continent":"Asia","pattern":"horizontal-tricolor-crescent","palette":"blue-red-green-white"},
{"code":"bh","name":"Baréin","capital":"Manama","continent":"Asia","pattern":"serrated-bicolor","palette":"white-red"},
{"code":"bd","name":"Bangladés","capital":"Daca","continent":"Asia","pattern":"circle-disc","palette":"green-red"},
{"code":"bt","name":"Bután","capital":"Timbu","continent":"Asia","pattern":"diagonal-dragon","palette":"yellow-orange-white"},
{"code":"bn","name":"Brunéi","capital":"Bandar Seri Begawan","continent":"Asia","pattern":"diagonal-emblem","palette":"yellow-white-black-red"},
{"code":"kh","name":"Camboya","capital":"Nom Pen","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"blue-red-white"},
{"code":"cn","name":"China","capital":"Pekín","continent":"Asia","pattern":"canton-stars","palette":"red-yellow"},
{"code":"ge","name":"Georgia","capital":"Tiflis","continent":"Asia","pattern":"cross-other","palette":"white-red"},
{"code":"in","name":"India","capital":"Nueva Delhi","continent":"Asia","pattern":"horizontal-tricolor-wheel","palette":"orange-white-green-blue"},
{"code":"id","name":"Indonesia","capital":"Yakarta","continent":"Asia","pattern":"horizontal-bicolor","palette":"red-white"},
{"code":"ir","name":"Irán","capital":"Teherán","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"green-white-red"},
{"code":"iq","name":"Irak","capital":"Bagdad","continent":"Asia","pattern":"horizontal-tricolor-text","palette":"red-white-black-green"},
{"code":"il","name":"Israel","capital":"Jerusalén","continent":"Asia","pattern":"star-of-david","palette":"blue-white"},
{"code":"jp","name":"Japón","capital":"Tokio","continent":"Asia","pattern":"circle-disc","palette":"white-red"},
{"code":"jo","name":"Jordania","capital":"Amán","continent":"Asia","pattern":"triangle-hoist-star","palette":"black-white-green-red"},
{"code":"kz","name":"Kazajistán","capital":"Astaná","continent":"Asia","pattern":"plain-emblem-center","palette":"blue-yellow"},
{"code":"kw","name":"Kuwait","capital":"Kuwait","continent":"Asia","pattern":"horizontal-tricolor-trapezoid","palette":"green-white-red-black"},
{"code":"kg","name":"Kirguistán","capital":"Biskek","continent":"Asia","pattern":"sun-rays","palette":"red-yellow"},
{"code":"la","name":"Laos","capital":"Vientián","continent":"Asia","pattern":"horizontal-tricolor-disc","palette":"red-blue-white"},
{"code":"lb","name":"Líbano","capital":"Beirut","continent":"Asia","pattern":"horizontal-tricolor-tree","palette":"red-white-green"},
{"code":"my","name":"Malasia","capital":"Kuala Lumpur","continent":"Asia","pattern":"canton-stars-stripes","palette":"red-white-blue-yellow"},
{"code":"mv","name":"Maldivas","capital":"Malé","continent":"Asia","pattern":"rectangle-crescent","palette":"red-green-white"},
{"code":"mn","name":"Mongolia","capital":"Ulán Bator","continent":"Asia","pattern":"vertical-tricolor-emblem","palette":"red-blue-yellow"},
{"code":"mm","name":"Myanmar","capital":"Naipyidó","continent":"Asia","pattern":"horizontal-tricolor-star","palette":"yellow-green-red-white"},
{"code":"np","name":"Nepal","capital":"Katmandú","continent":"Asia","pattern":"double-pennant","palette":"red-blue-white"},
{"code":"kp","name":"Corea del Norte","capital":"Pionyang","continent":"Asia","pattern":"horizontal-red-band-star","palette":"blue-red-white"},
{"code":"om","name":"Omán","capital":"Mascate","continent":"Asia","pattern":"horizontal-tricolor-emblem","palette":"white-red-green"},
{"code":"pk","name":"Pakistán","capital":"Islamabad","continent":"Asia","pattern":"vertical-bicolor-crescent","palette":"green-white"},
{"code":"ps","name":"Palestina","capital":"Ramala","continent":"Asia","pattern":"triangle-hoist","palette":"black-white-green-red"},
{"code":"ph","name":"Filipinas","capital":"Manila","continent":"Asia","pattern":"horizontal-bicolor-triangle-sun","palette":"blue-red-white-yellow"},
{"code":"qa","name":"Catar","capital":"Doha","continent":"Asia","pattern":"serrated-bicolor","palette":"maroon-white"},
{"code":"sa","name":"Arabia Saudita","capital":"Riad","continent":"Asia","pattern":"plain-emblem-text","palette":"green-white"},
{"code":"sg","name":"Singapur","capital":"Singapur","continent":"Asia","pattern":"horizontal-bicolor-crescent","palette":"red-white"},
{"code":"kr","name":"Corea del Sur","capital":"Seúl","continent":"Asia","pattern":"taegeuk","palette":"white-red-blue-black"},
{"code":"lk","name":"Sri Lanka","capital":"Sri Jayawardenapura Kotte","continent":"Asia","pattern":"complex-lion","palette":"yellow-maroon-green-orange"},
{"code":"sy","name":"Siria","capital":"Damasco","continent":"Asia","pattern":"horizontal-tricolor-stars","palette":"red-white-black-green"},
{"code":"tj","name":"Tayikistán","capital":"Dusambé","continent":"Asia","pattern":"horizontal-tricolor-crown","palette":"red-white-green-yellow"},
{"code":"th","name":"Tailandia","capital":"Bangkok","continent":"Asia","pattern":"horizontal-multi","palette":"red-white-blue"},
{"code":"tl","name":"Timor Oriental","capital":"Dili","continent":"Asia","pattern":"triangle-star","palette":"red-black-yellow-white"},
{"code":"tr","name":"Turquía","capital":"Ankara","continent":"Asia","pattern":"crescent-star","palette":"red-white"},
{"code":"tm","name":"Turkmenistán","capital":"Asjabad","continent":"Asia","pattern":"vertical-band-carpet","palette":"green-red-white"},
{"code":"ae","name":"Emiratos Árabes Unidos","capital":"Abu Dabi","continent":"Asia","pattern":"horizontal-tricolor-band","palette":"green-white-black-red"},
{"code":"uz","name":"Uzbekistán","capital":"Taskent","continent":"Asia","pattern":"horizontal-tricolor-crescent","palette":"blue-white-green-red"},
{"code":"vn","name":"Vietnam","capital":"Hanói","continent":"Asia","pattern":"single-star","palette":"red-yellow"},
{"code":"ye","name":"Yemen","capital":"Saná","continent":"Asia","pattern":"horizontal-tricolor","palette":"red-white-black"},

{"code":"al","name":"Albania","capital":"Tirana","continent":"Europa","pattern":"horizontal-eagle","palette":"red-black"},
{"code":"ad","name":"Andorra","capital":"Andorra la Vieja","continent":"Europa","pattern":"vertical-tricolor-emblem","palette":"blue-yellow-red"},
{"code":"at","name":"Austria","capital":"Viena","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white"},
{"code":"by","name":"Bielorrusia","capital":"Minsk","continent":"Europa","pattern":"horizontal-bicolor-pattern","palette":"red-green-white"},
{"code":"be","name":"Bélgica","capital":"Bruselas","continent":"Europa","pattern":"vertical-tricolor","palette":"black-yellow-red"},
{"code":"ba","name":"Bosnia y Herzegovina","capital":"Sarajevo","continent":"Europa","pattern":"diagonal-stars","palette":"blue-yellow-white"},
{"code":"bg","name":"Bulgaria","capital":"Sofía","continent":"Europa","pattern":"horizontal-tricolor","palette":"white-green-red"},
{"code":"hr","name":"Croacia","capital":"Zagreb","continent":"Europa","pattern":"horizontal-tricolor-shield","palette":"red-white-blue"},
{"code":"cy","name":"Chipre","capital":"Nicosia","continent":"Europa","pattern":"plain-emblem-map","palette":"white-green"},
{"code":"cz","name":"Chequia","capital":"Praga","continent":"Europa","pattern":"triangle-hoist","palette":"white-red-blue"},
{"code":"dk","name":"Dinamarca","capital":"Copenhague","continent":"Europa","pattern":"cross-nordic","palette":"red-white"},
{"code":"ee","name":"Estonia","capital":"Tallin","continent":"Europa","pattern":"horizontal-tricolor","palette":"blue-black-white"},
{"code":"fi","name":"Finlandia","capital":"Helsinki","continent":"Europa","pattern":"cross-nordic","palette":"white-blue"},
{"code":"fr","name":"Francia","capital":"París","continent":"Europa","pattern":"vertical-tricolor","palette":"blue-white-red"},
{"code":"de","name":"Alemania","capital":"Berlín","continent":"Europa","pattern":"horizontal-tricolor","palette":"black-red-gold"},
{"code":"gr","name":"Grecia","capital":"Atenas","continent":"Europa","pattern":"stripes-canton-cross","palette":"blue-white"},
{"code":"hu","name":"Hungría","capital":"Budapest","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-green"},
{"code":"is","name":"Islandia","capital":"Reikiavik","continent":"Europa","pattern":"cross-nordic","palette":"blue-red-white"},
{"code":"ie","name":"Irlanda","capital":"Dublín","continent":"Europa","pattern":"vertical-tricolor","palette":"green-white-orange"},
{"code":"it","name":"Italia","capital":"Roma","continent":"Europa","pattern":"vertical-tricolor","palette":"green-white-red"},
{"code":"lv","name":"Letonia","capital":"Riga","continent":"Europa","pattern":"horizontal-tricolor","palette":"maroon-white"},
{"code":"li","name":"Liechtenstein","capital":"Vaduz","continent":"Europa","pattern":"horizontal-bicolor-crown","palette":"blue-red-gold"},
{"code":"lt","name":"Lituania","capital":"Vilna","continent":"Europa","pattern":"horizontal-tricolor","palette":"yellow-green-red"},
{"code":"lu","name":"Luxemburgo","capital":"Luxemburgo","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-blue"},
{"code":"mt","name":"Malta","capital":"La Valeta","continent":"Europa","pattern":"vertical-bicolor-cross","palette":"white-red"},
{"code":"md","name":"Moldavia","capital":"Chisináu","continent":"Europa","pattern":"vertical-tricolor-emblem","palette":"blue-yellow-red"},
{"code":"mc","name":"Mónaco","capital":"Mónaco","continent":"Europa","pattern":"horizontal-bicolor","palette":"red-white"},
{"code":"me","name":"Montenegro","capital":"Podgorica","continent":"Europa","pattern":"plain-emblem-border","palette":"red-gold"},
{"code":"nl","name":"Países Bajos","capital":"Ámsterdam","continent":"Europa","pattern":"horizontal-tricolor","palette":"red-white-blue"},
{"code":"mk","name":"Macedonia del Norte","capital":"Skopie","continent":"Europa","pattern":"sun-rays","palette":"red-yellow"},
{"code":"no","name":"Noruega","capital":"Oslo","continent":"Europa","pattern":"cross-nordic","palette":"red-white-blue"},
{"code":"pl","name":"Polonia","capital":"Varsovia","continent":"Europa","pattern":"horizontal-bicolor","palette":"white-red"},
{"code":"pt","name":"Portugal","capital":"Lisboa","continent":"Europa","pattern":"vertical-bicolor-emblem","palette":"green-red-yellow"},
{"code":"ro","name":"Rumanía","capital":"Bucarest","continent":"Europa","pattern":"vertical-tricolor","palette":"blue-yellow-red"},
{"code":"ru","name":"Rusia","capital":"Moscú","continent":"Europa","pattern":"horizontal-tricolor","palette":"white-blue-red"},
{"code":"sm","name":"San Marino","capital":"San Marino","continent":"Europa","pattern":"horizontal-bicolor-emblem","palette":"white-blue"},
{"code":"rs","name":"Serbia","capital":"Belgrado","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"red-blue-white"},
{"code":"sk","name":"Eslovaquia","capital":"Bratislava","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"white-blue-red"},
{"code":"si","name":"Eslovenia","capital":"Liubliana","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"white-blue-red"},
{"code":"es","name":"España","capital":"Madrid","continent":"Europa","pattern":"horizontal-tricolor-emblem","palette":"red-yellow"},
{"code":"se","name":"Suecia","capital":"Estocolmo","continent":"Europa","pattern":"cross-nordic","palette":"blue-yellow"},
{"code":"ch","name":"Suiza","capital":"Berna","continent":"Europa","pattern":"cross-other","palette":"red-white"},
{"code":"ua","name":"Ucrania","capital":"Kiev","continent":"Europa","pattern":"horizontal-bicolor","palette":"blue-yellow"},
{"code":"gb","name":"Reino Unido","capital":"Londres","continent":"Europa","pattern":"union-jack","palette":"blue-red-white"},
{"code":"va","name":"Vaticano","capital":"Ciudad del Vaticano","continent":"Europa","pattern":"vertical-bicolor-emblem","palette":"yellow-white"},

{"code":"ca","name":"Canadá","capital":"Ottawa","continent":"América","pattern":"vertical-bicolor-leaf","palette":"red-white"},
{"code":"us","name":"Estados Unidos","capital":"Washington D. C.","continent":"América","pattern":"canton-stars-stripes","palette":"red-white-blue"},
{"code":"mx","name":"México","capital":"Ciudad de México","continent":"América","pattern":"vertical-tricolor-emblem","palette":"green-white-red"},
{"code":"bz","name":"Belice","capital":"Belmopán","continent":"América","pattern":"plain-emblem-border","palette":"blue-red-white"},
{"code":"cr","name":"Costa Rica","capital":"San José","continent":"América","pattern":"horizontal-multi","palette":"blue-white-red"},
{"code":"sv","name":"El Salvador","capital":"San Salvador","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"blue-white-gold"},
{"code":"gt","name":"Guatemala","capital":"Ciudad de Guatemala","continent":"América","pattern":"vertical-tricolor-emblem","palette":"blue-white-green"},
{"code":"hn","name":"Honduras","capital":"Tegucigalpa","continent":"América","pattern":"horizontal-tricolor-stars","palette":"blue-white"},
{"code":"ni","name":"Nicaragua","capital":"Managua","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"blue-white-yellow"},
{"code":"pa","name":"Panamá","capital":"Ciudad de Panamá","continent":"América","pattern":"quartered-stars","palette":"white-blue-red"},
{"code":"ag","name":"Antigua y Barbuda","capital":"Saint John's","continent":"América","pattern":"sun-rays-triangle","palette":"black-blue-white-red-yellow"},
{"code":"bs","name":"Bahamas","capital":"Nasáu","continent":"América","pattern":"horizontal-tricolor-triangle","palette":"blue-yellow-black"},
{"code":"bb","name":"Barbados","capital":"Bridgetown","continent":"América","pattern":"vertical-tricolor-trident","palette":"blue-yellow-black"},
{"code":"cu","name":"Cuba","capital":"La Habana","continent":"América","pattern":"stripes-triangle-star","palette":"blue-white-red"},
{"code":"dm","name":"Dominica","capital":"Roseau","continent":"América","pattern":"plain-emblem-cross","palette":"green-yellow-black-white-red"},
{"code":"do","name":"República Dominicana","capital":"Santo Domingo","continent":"América","pattern":"cross-quartered","palette":"blue-red-white"},
{"code":"gd","name":"Granada","capital":"Saint George's","continent":"América","pattern":"border-triangle-nutmeg","palette":"yellow-green-red"},
{"code":"ht","name":"Haití","capital":"Puerto Príncipe","continent":"América","pattern":"horizontal-bicolor-emblem","palette":"blue-red"},
{"code":"jm","name":"Jamaica","capital":"Kingston","continent":"América","pattern":"saltire","palette":"black-green-yellow"},
{"code":"kn","name":"San Cristóbal y Nieves","capital":"Basseterre","continent":"América","pattern":"diagonal-stars","palette":"green-black-red-yellow"},
{"code":"lc","name":"Santa Lucía","capital":"Castries","continent":"América","pattern":"triangle-emblem","palette":"blue-black-yellow-white"},
{"code":"vc","name":"San Vicente y las Granadinas","capital":"Kingstown","continent":"América","pattern":"vertical-tricolor-diamonds","palette":"blue-yellow-green"},
{"code":"tt","name":"Trinidad y Tobago","capital":"Puerto España","continent":"América","pattern":"diagonal-bicolor","palette":"red-black-white"},
{"code":"ar","name":"Argentina","capital":"Buenos Aires","continent":"América","pattern":"horizontal-tricolor-sun","palette":"blue-white-yellow"},
{"code":"bo","name":"Bolivia","capital":"Sucre","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"red-yellow-green"},
{"code":"br","name":"Brasil","capital":"Brasilia","continent":"América","pattern":"plain-emblem-globe","palette":"green-yellow-blue-white"},
{"code":"cl","name":"Chile","capital":"Santiago","continent":"América","pattern":"quartered-star","palette":"white-red-blue"},
{"code":"co","name":"Colombia","capital":"Bogotá","continent":"América","pattern":"horizontal-multi","palette":"yellow-blue-red"},
{"code":"ec","name":"Ecuador","capital":"Quito","continent":"América","pattern":"horizontal-multi-emblem","palette":"yellow-blue-red"},
{"code":"gy","name":"Guyana","capital":"Georgetown","continent":"América","pattern":"triangle-arrowhead","palette":"green-red-yellow-black-white"},
{"code":"py","name":"Paraguay","capital":"Asunción","continent":"América","pattern":"horizontal-tricolor-emblem","palette":"red-white-blue"},
{"code":"pe","name":"Perú","capital":"Lima","continent":"América","pattern":"vertical-tricolor","palette":"red-white"},
{"code":"sr","name":"Surinam","capital":"Paramaribo","continent":"América","pattern":"horizontal-multi-star","palette":"green-white-red-yellow"},
{"code":"uy","name":"Uruguay","capital":"Montevideo","continent":"América","pattern":"stripes-sun","palette":"white-blue-yellow"},
{"code":"ve","name":"Venezuela","capital":"Caracas","continent":"América","pattern":"horizontal-tricolor-stars","palette":"yellow-blue-red-white"},

{"code":"au","name":"Australia","capital":"Canberra","continent":"Oceanía","pattern":"canton-stars","palette":"blue-white-red"},
{"code":"fj","name":"Fiyi","capital":"Suva","continent":"Oceanía","pattern":"canton-shield","palette":"blue-white-red"},
{"code":"ki","name":"Kiribati","capital":"Tarawa Sur","continent":"Oceanía","pattern":"horizontal-sun-bird","palette":"red-yellow-blue-white"},
{"code":"mh","name":"Islas Marshall","capital":"Majuro","continent":"Oceanía","pattern":"diagonal-star","palette":"blue-orange-white"},
{"code":"fm","name":"Micronesia","capital":"Palikir","continent":"Oceanía","pattern":"plain-stars","palette":"blue-white"},
{"code":"nr","name":"Nauru","capital":"Yaren","continent":"Oceanía","pattern":"horizontal-star","palette":"blue-yellow-white"},
{"code":"nz","name":"Nueva Zelanda","capital":"Wellington","continent":"Oceanía","pattern":"canton-stars-southern-cross","palette":"blue-white-red"},
{"code":"pw","name":"Palaos","capital":"Ngerulmud","continent":"Oceanía","pattern":"circle-disc","palette":"blue-yellow"},
{"code":"pg","name":"Papúa Nueva Guinea","capital":"Port Moresby","continent":"Oceanía","pattern":"diagonal-bicolor-stars","palette":"red-black-yellow-white"},
{"code":"ws","name":"Samoa","capital":"Apia","continent":"Oceanía","pattern":"canton-stars","palette":"red-blue-white"},
{"code":"sb","name":"Islas Salomón","capital":"Honiara","continent":"Oceanía","pattern":"diagonal-stripe-stars","palette":"blue-green-yellow-white"},
{"code":"to","name":"Tonga","capital":"Nukualofa","continent":"Oceanía","pattern":"canton-cross","palette":"red-white"},
{"code":"tv","name":"Tuvalu","capital":"Funafuti","continent":"Oceanía","pattern":"canton-stars-map","palette":"blue-white-yellow"},
{"code":"vu","name":"Vanuatu","capital":"Port Vila","continent":"Oceanía","pattern":"diagonal-emblem","palette":"black-red-green-yellow"}
];
